name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  mac:
    name: macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ['16.0']
        config: ['debug']
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Swift Version
      run: swift --version
    - name: Run ${{ matrix.xcode }} Tests
      run: make CONFIG=${{ matrix.config }} test-swift

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: make DOCKER_PLATFORM=linux/amd64 test-linux
